name: Reusable Markdown Lint

on:
  workflow_call:
    inputs:
      markdownlint-cli2-version:
        description: "markdownlint-cli2-action version (commit SHA)"
        required: false
        type: string
        default: "07035fd053f7be764496c0f8d8f9f41f98305101"
      runs-on:
        description: "Runner label"
        required: false
        type: string
        default: "ubuntu-latest"

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: DavidAnson/markdownlint-cli2-action@8de2aa07cae85fd17c0b35642db70cf5495f1d25 # v24.0.0
