name: Reusable Markdown Link Check

on:
  workflow_call:
    inputs:
      lychee-args:
        description: "Arguments passed to lychee"
        required: false
        type: string
        default: '--config .lychee.toml "**/*.md"'
      fail-on-error:
        description: "Whether to fail the workflow on broken links"
        required: false
        type: boolean
        default: false
      runs-on:
        description: "Runner label"
        required: false
        type: string
        default: "ubuntu-latest"

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: ${{ inputs.lychee-args }}
          fail: ${{ inputs.fail-on-error }}
