name: Reusable Spell Check

on:
  workflow_call:
    inputs:
      config:
        description: "Path to cspell configuration file"
        required: false
        type: string
        default: ".cspell.json"
      files:
        description: "Glob pattern for files to check"
        required: false
        type: string
        default: "**/*.md"
      runs-on:
        description: "Runner label"
        required: false
        type: string
        default: "ubuntu-latest"

permissions:
  contents: read

jobs:
  spelling:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8.4.0
        with:
          config: ${{ inputs.config }}
          files: ${{ inputs.files }}
