name: Reusable Spell Check

on:
  workflow_call:
    inputs:
      config:
        description: "Path to cspell configuration file"
        required: false
        type: string
        default: ".cspell.json"
      files:
        description: "Glob pattern for files to check"
        required: false
        type: string
        default: "**/*.md"
      runs-on:
        description: "Runner label"
        required: false
        type: string
        default: "ubuntu-latest"

permissions:
  contents: read

jobs:
  spelling:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8.4.0
        with:
          config: ${{ inputs.config }}
          files: ${{ inputs.files }}
