name: Reusable Spell Check

on:
  workflow_call:
    inputs:
      config:
        description: "Path to cspell configuration file"
        required: false
        type: string
        default: ".cspell.json"
      files:
        description: "Glob pattern for files to check"
        required: false
        type: string
        default: "**/*.md"
      runs-on:
        description: "Runner label"
        required: false
        type: string
        default: "ubuntu-latest"

permissions:
  contents: read

jobs:
  spelling:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: streetsidesoftware/cspell-action@e0668cf020899e887ee8ad4d173c31738a79eae8 # v9.0.1
        with:
          config: ${{ inputs.config }}
          files: ${{ inputs.files }}
